version: '3.5'

services:
  d3-iroha:
    image: hyperledger/iroha:1.1.0
    ports:
      - 50051:50051
    depends_on:
      - d3-iroha-postgres
    tty: true
    environment:
      - KEY=keys/node0
    entrypoint:
      - /opt/iroha_data/entrypoint.sh
    volumes:
      - iroha_block_store:/tmp/block_store
      - ./iroha:/opt/iroha_data
    networks:
      - d3-network

  d3-iroha-postgres:
    image: postgres:9.5
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - /var/lib/postgresql/data
    networks:
      - d3-network

volumes:
  iroha_block_store:

networks:
  d3-network:
